Mini challenge 2
acamposhd/react-certification-2021 pull request #3
Opened 2021-07-27 04:25 UTC by acamposhd

2021-07-27 04:29 UTC, acamposhd commented
Using create-react-app, what do we need to set up for testing?
CRA comes with a set of predefined tools that help us to develop, test and build our project.

What components are worth to test in your development?
I think we must test core components, those functions that has sensitive data

Can you apply TDD once you already created components?
Yes, although it should be first tests and then code we can write tests latter, TDD is the methodology to develop thinking always in test scenarios.

2021-07-29 20:45 UTC, AlejandroSeguraWIZ requested changes
I have some comments regarding your work, but well done!
```
- There are some empty files. Remove them, please. i.e. `Layout.styles.css`
- The structure of the project is not clear enough. I do recommend you to follow the next pattern:
__tests__
     App.test.js
App.styles.js
App.js
components/
     /VideoLayer
           __tests__
                VideoLayer.test.js
           VideoLayer.styles.js
           VideoLayer.js
           index.js
... and so on
```

2021-07-29 20:47 UTC, AlejandroSeguraWIZ requested changes

2021-07-29 20:47 UTC, AlejandroSeguraWIZ commented on src/components/NavBar/NavBar.component.jsx
> +export default NavBar;
You should group all the styles in another file (i.e. NavBar.styles.js) and move the component itself to a file with a more concise name like `Navbar.js`. Then export that component through `index.js`

2021-08-06 01:37 UTC, AlejandroSeguraWIZ approved these changes

2021-08-27 14:29 UTC, merged